#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ipython
Version  : 5.2.0
Release  : 1
URL      : https://pypi.python.org/packages/df/44/0eee6ed339641d88e2be32ddfd695a39c954b66e5a10ba701629ce3454e9/ipython-5.2.0.tar.gz
Source0  : https://pypi.python.org/packages/df/44/0eee6ed339641d88e2be32ddfd695a39c954b66e5a10ba701629ce3454e9/ipython-5.2.0.tar.gz
Summary  : IPython: Productive Interactive Computing
Group    : Development/Tools
License  : BSD-3-Clause BSD-3-Clause-Clear
Requires: ipython-bin
Requires: ipython-python
Requires: ipython-doc
BuildRequires : Pygments
BuildRequires : decorator
BuildRequires : pbr
BuildRequires : pickleshare
BuildRequires : pip
BuildRequires : prompt_toolkit
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : simplegeneric
BuildRequires : traitlets

%description
.. image:: https://codecov.io/github/ipython/ipython/coverage.svg?branch=master
:target: https://codecov.io/github/ipython/ipython?branch=master

%package bin
Summary: bin components for the ipython package.
Group: Binaries

%description bin
bin components for the ipython package.


%package doc
Summary: doc components for the ipython package.
Group: Documentation

%description doc
doc components for the ipython package.


%package python
Summary: python components for the ipython package.
Group: Default

%description python
python components for the ipython package.


%prep
%setup -q -n ipython-5.2.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1485747916
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1485747916
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/iptest
/usr/bin/iptest2
/usr/bin/iptest3
/usr/bin/ipython
/usr/bin/ipython2
/usr/bin/ipython3

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
